/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type S4pOperationType = "action_in_app" | "ai_data_trans" | "condition" | "data_trans" | "loop" | "trigger";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface S4pApps {
  id: Generated<string>;
  integration_id: string;
  name: string;
  ui_name: string;
}

export interface S4pIntegrations {
  credentials: string | null;
  developer_account_email: string;
  id: Generated<string>;
  name: string;
  ui_name: string | null;
}

export interface S4pOperations {
  configuration: Json;
  id: Generated<string>;
  next_operation_id_false: string | null;
  next_operation_id_true: string | null;
  previous_operation_id: string | null;
  type: S4pOperationType;
  workflow_id: string;
}

export interface S4pUserIntegrations {
  access_token: string | null;
  access_token_expiry: Timestamp | null;
  account_id: string;
  email: string;
  id: Generated<string>;
  integration_id: string;
  refresh_token: string | null;
  user_id: string;
}

export interface S4pUsers {
  email: string;
  first_name: string;
  id: Generated<string>;
  last_name: string;
  password: string;
}

export interface S4pWorkflows {
  id: Generated<string>;
  name: string;
  user_id: string;
}

export interface DB {
  "s4p.apps": S4pApps;
  "s4p.integrations": S4pIntegrations;
  "s4p.operations": S4pOperations;
  "s4p.user_integrations": S4pUserIntegrations;
  "s4p.users": S4pUsers;
  "s4p.workflows": S4pWorkflows;
}
